version: '3.8'

services:
  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
  # discord-client-api:                       # Image for current Docker container for your application
  #   image: client-api:latest                # The Docker image which needs to be runned
  #   container_name: discord-client-api      # Container name of current image (Same as service name)
  #   restart: always                         # Always restart on failure for example
  # discord-web-dashboard:
  #   image: discord-dashboard:latest
  #   container_name: discord-web-dashboard
  #   restart: always
